---
- name: restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted

- name: restart timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: restart chronyd
  service:
    name: chronyd
    state: restarted
